### ISSUE TITLE
Questions about usage and output

### ISSUE THREAD

**Issue by Faewks** [GenomiqueENS/toulligQC#10]
Hi,
first of all: Thank you for this tool!

I have some question related the output and the usage of ToulligQC.
I'm running version 2.2
- at the end of the `Readme.md` you mentioned that the output should look like this: 
RUN_ID
├── report.html
├── report.data
└── images
      └── plots.html
      └── plot.png

  For me it looks like this after this program call: 

`toulligqc --report-name <ReportName> \`
`--telemetry-source /Path/To/sequencing_telemetry.js \`
`--sequencing-summary-source /PAth/To/sequencing_summary.txt \`
`--output-directory /Path/To/OutputDirectory/`

RUN_ID
├── report.html
├── report.data
└── images
      └── plots.html

  Do I miss a option or do I missunderstand your outputgraph?

- The second thing I have to ask, is if the Kit "SQK-PCB109" is not (yet) included into ToulligQC? I have tried it with following command:

`toulligqc --report-name <ReportName> \`
`--telemetry-source /Path/To/sequencing_telemetry.js \`
`--sequencing-summary-source /Path/To/sequencing_summary.txt \`
`--sequencing-summary-source /Path/To/barcoding_summary_pass.txt \`
`--sequencing-summary-source /Path/To/barcoding_summary_fail.txt \`
`--barcodes BP01,BP02,BP03,BP04,BP05,BP06,BP07,BP08,BP09,BP10,BP11,BP12 \`
`--output-directory /Path/To/OutputDirectory/`

and got `ERROR: No known barcode found in provided list of barcodes`

Thank you in advance.

**Comment by jourdren** [comment]
Dear Faewks,

Thanks for reporting this issue. I've just made a commit to fix this issue https://github.com/GenomiqueENS/toulligQC/commit/e7c3a86cf458315a6e2e3e9d7dfb9a5b40f7d872.

However, you can bypass this issue if in the **barcode_arrangement** column of your `sequencing_summary.txt` file, the barcodes are named like barcodeXX. In this case, just rename in your command line BPXX by barcodeXX, and ToulligQC will work!

Tell me, if this workaround works for you.

Best regards,

Laurent.

**Comment by jourdren** [comment]
Dear Faewks,

Great news to hear.

Unfortunately, ToulligQC cannot save PNG images as the plots are interactive and made with Plotly that use HTML/Javascript behind. You must use screenshot feature of your OS/web browser (Firefox's one is great) to save plots as PNG images.

Best regards,

Laurent.

PS: I will soon close this issue.

**Comment by Faewks** [comment]
Ok,
Thank you for the tipps and I will close this issue.

Best regards,
Faewks.
