### ISSUE TITLE
how to extract a fast5 file from Npore run data to use as sequencing_telemetry file substitute

### ISSUE THREAD

**Issue by nwhand** [GenomiqueENS/toulligQC#13]
Hi, A colleague has shown me reports generated with toulligQC that would be great for me. However I am just a wet lab person! The output from the Nanopore Mk1c does not include a 'sequencing_telemetry' file. I see from the Github page that a fast5 file would be a fine substitute. Assuming this is true and the fastest way for me to get a report is to add a fast5 file, how do i isolate a fast5 file from the package of 4000 that is generated by the minion? (i think the default size of fast5 folders is 4000 reads).

Thanks,
Nick H.

**Comment by jourdren** [comment]
Dear @nwhand, you can use any of the fast5 file produced by run the run as all the fast5 files contain metadata about the run!

**Comment by nwhand** [comment]
@jourdren, thank you, how do i isolate or extract a fast5 file from a folder of fast5 files? (the minion groups together 4000 fast5 files in one folder).

**Comment by jourdren** [comment]
You just had to set the path of just one Fast5 file in the command line. As an example, see the `--fast5-source` the argument in the following command line:
```bash
$ toulligqc --report-name FAF0256 \
            --barcoding \
            --fast5-source /path/to/the/run/no_sample/20220728_1551_MC-110337_FAT79338_15385417/fast5/ FAT79338_9a380b24_0.fast5 \
            --sequencing-summary-source /path/to/basecaller/output/sequencing_summary.txt \
            --sequencing-summary-source /path/to/basecaller/output/barcoding_summary_pass.txt \         # (optional)
            --sequencing-summary-source /path/to/basecaller/output/barcoding_summary_fail.txt \         # (optional)
            --sequencing-summary-1dsqr-source /path/to/basecaller/output/sequencing_1dsqr_summary.txt \ # (optional)
            --sequencing-summary-1dsqr-source /path/to/basecaller/output/barcoding_summary_pass.txt \   # (optional)
            --sequencing-summary-1dsqr-source /path/to/basecaller/output/barcoding_summary_fail.txt \   # (optional)
            --html-report-path /path/to/output/report.html \
            --data-report-path /path/to/output/report.data \                                            # (optional)
            --barcodes BC01,BC02,BC03
```
