### ISSUE TITLE
Numpy 1.24 compatibility

### ISSUE THREAD

**Issue by seann27** [GenomiqueENS/toulligQC#14]
In the event anyone tries to run this with numpy 1.24, you just need to change the numpy type casting for booleans in line 355 of sequencing_summary_extractor.py 

from

        sequencing_summary_datatypes = {
            'channel': np.int16,
            'start_time': np.float64,
            'passes_filtering': np.bool, <--------------------------------------------
            'sequence_length_template': np.uint32,
            'mean_qscore_template': np.float32,
            'duration': np.float32}

to

        sequencing_summary_datatypes = {
            'channel': np.int16,
            'start_time': np.float64,
            'passes_filtering': np.bool_, <--------------------------------------------
            'sequence_length_template': np.uint32,
            'mean_qscore_template': np.float32,
            'duration': np.float32}

then it seems to work as expected. cheers

**Comment by alihamraoui** [comment]
Dear @

Thanks for reporting this issue.

I've just fixed it with commit  013690325083ee0c7c20a08cc5354338a9010115

A new version of ToulligQC will be published soon.

Best,
Ali
