### ISSUE TITLE
Multiple summary and telemetry files

### ISSUE THREAD

**Issue by MustafaElshani** [GenomiqueENS/toulligQC#15]
It seems toulligQC will  not work with multiple summary or telemetry files, like those given when basecalled using `guppy_supervisor`. I tried to concatenate the files it gives the following error for telemetry 

```
json.decoder.JSONDecodeError: Extra data: line 252161 column 2 (char 5928761)
```
any help appreciated 
Mustafa

**Comment by alihamraoui** [comment]
Hi Mustafa,
As I understand, you want to generate a single report for two distinct runs. 
ToulligQC is not considering this case. However, you can manually concatenate the both summary files. The telemetry file is optional, but you can give only one file. 
best
Ali
