### ISSUE TITLE
toulligqc for pod5 format

### ISSUE THREAD

**Issue by ogrecio** [GenomiqueENS/toulligQC#18]
Hi!
thank you for providing this tool. I have new projects that are stored in pod5. The tool seems to not be compatible with this format.
Is there any wayaround to this?
Thank you in advance.
Kind regards,
Oscar

**Comment by jourdren** [comment]
Dear @ogrecio,

We plan to handle POD5 files in addition to Fast5 files in the coming months!
Meanwhile, you can use the `sequencing_telemetry.js` file as run metadata source.

Best regards,
Laurent.
