### ISSUE TITLE
Barcodes in dorado output

### ISSUE THREAD

**Issue by phpeters** [GenomiqueENS/toulligQC#22]
Hej,

Thanks for this really pretty tool! I encountered a small issue when using it with dorado's output:

a) When demultiplexing with dorado demux, toulligQC (v2.6) does not produce the barcode plots. This is due to the sequencing_summary_extractor.py which recognized the column "barcode_arrangement" but dorado's column name is only "barcode". 
I used dorado v0.5.1 and provided the barcodes via sample-sheet and demultiplexing kit (dorado basecaller ${basecallmodel} pod5/ --sample-sheet ${sampleSheet} $demuxKit ). When I changed my sequencing_summary.txt column to "barcode_arrangement", toulligQC produced the plots properly.

b) Is it possible to skip/modify the barcode-name check in toulligqc.py (ctrl+F: "Get barcode selection")? I'm have our lab's (integer) sampleID's as barcode names in the sequeuncing_summary and would have to add "BC" or "barcode" as prefix such that I don't et the error "ERROR: No known barcode found in provided list of barcodes". In dorado, you can specify now your own [custom barcode](https://github.com/nanoporetech/dorado/blob/release-v0.5.3/documentation/CustomBarcodes.md) sets as well with different names. That would be cool to be changed in toulligQC!

Thanks a ton and have a great week!
Philipp

**Comment by alihamraoui** [comment]
Hej @phpeters,

Thank you for the great suggestions; they contribute to improving ToulligQC.

I addressed points (a) and (b) in commits 055b15e352d043974f597a5652697ec91a28cb00 and c387d9c2a83982eafc3acbbd7b5a44c51ffb471e.

These changes will be deployed in the next version of ToulligQC, coming soon.

Thanks again!
Ali

**Comment by phpeters** [comment]
Merci for the quick fix, Ali! I'll try it out soon. All the best!
Philipp
