### ISSUE TITLE
v2.6 on docker

### ISSUE THREAD

**Issue by blanleung** [GenomiqueENS/toulligQC#26]
Hi there,

Thanks for the great tool!

Any plan to release latest version (v2.6) on docker? Mainly for pod5 support. Thanks.

Cheers
Ben

**Comment by alihamraoui** [comment]
Hi @blanleung,

Thank you for using ToulligQC!

ToulligQC v2.6 is already available on Docker. You can pull it using the following command:

```bash
docker pull genomicpariscentre/toulligqc:2.6
```
I hope this answers your question. Please let me know if you encounter any issues.

Best regards,
Ali

**Comment by blanleung** [comment]
Hi Ali,

Sorry I just paid attention to the most recents addition to docker hub (v2.5.7) hence why I assumed 2.6 was not released yet. My bad

Thanks
Ben
