### ISSUE TITLE
showing barcoded reads info still not fixed

### ISSUE THREAD

**Issue by ZTehrani** [GenomiqueENS/toulligQC#27]
Hello,

Thank you for developing this great tool. 

I did the solution mentioned in issue #25 (changing column 'barcode' to 'barcode_arrangement'), and now in my report the barcoded reads section is there but with no information. 

![image](https://github.com/GenomiqueENS/toulligQC/assets/77905953/4b9f4bd8-1f88-4c90-986c-90d10bf2a378)

While creating the report I got the following warning:

_Warning: The barcode barcode01 doesn't exist in input data
Warning: The barcode barcode02 doesn't exist in input data
Warning: The barcode barcode03 doesn't exist in input data
Warning: The barcode barcode04 doesn't exist in input data
Warning: The barcode barcode05 doesn't exist in input data
Warning: The barcode barcode06 doesn't exist in input data
Warning: The barcode barcode07 doesn't exist in input data
Warning: The barcode barcode08 doesn't exist in input data
Warning: The barcode barcode09 doesn't exist in input data
Warning: The barcode barcode10 doesn't exist in input data
Warning: The barcode barcode11 doesn't exist in input data
Warning: The barcode barcode12 doesn't exist in input data
Warning: The barcode barcode13 doesn't exist in input data
Warning: The barcode barcode14 doesn't exist in input data
Warning: The barcode barcode15 doesn't exist in input data_

These are the commands I ran and got same result with both:

**toulligqc --report-name** 'Sequencing Report' **--sequencing-summary-source** ..../basecalling/summary.txt **--pod5-source** ..../reads_pod5 **--html-report-path** ...../qc_report/report_barcoding.html **--data-report-path** ..../qc_report/report_barcoding.data **--barcoding --barcodes** SQK-NBD114-24_barcode01,SQK-NBD114-24_barcode02,SQK-NBD114-24_barcode03,SQK-NBD114-24_barcode04,SQK-NBD114-24_barcode05,SQK-NBD114-24_barcode06,SQK-NBD114-24_barcode07,SQK-NBD114-24_barcode08,SQK-NBD114-24_barcode09,SQK-NBD114-24_barcode10,SQK-NBD114-24_barcode11,SQK-NBD114-24_barcode12,SQK-NBD114-24_barcode13,SQK-NBD114-24_barcode14,SQK-NBD114-24_barcode15

**toulligqc --report-name** 'Sequencing Report' **--sequencing-summary-source** ..../basecalling/summary.txt **--pod5-source** ..../reads_pod5 **--html-report-path** ...../qc_report/report_barcoding.html **--data-report-path** ..../qc_report/report_barcoding.data **--barcoding --barcodes** barcode01,barcode02,barcode03,barcode04,barcode05,barcode06,barcode07,barcode08,barcode09,barcode10,barcode11,barcode12,barcode13,barcode14,barcode15

Would appreciate your help.

Thanks.

**Comment by alihamraoui** [comment]
Hello @ZTehrani,

Thank you for using ToulligQC.

Please note that ToulligQC 2.6 does not consider the new format of Dorado barcodes SQK-NBD114-24_barcode02 (barcodeing kit name _ barcode name).

A new **ToulligQC 2.7** version will be available tomorrow, which addresses the Dorado sequencing summaries.

In the meantime, you can use the command below to remove the kit name from the barcode:

```
sed 's/SQK-NBD114-24_//' summary.txt > summary_filtered.txt 
```

and then re-run your second command:
```
toulligqc --report-name 'Sequencing Report'  \
               --sequencing-summary-source ..../basecalling/summary_filtered.txt \
               --pod5-source ..../reads_pod5 \
               --html-report-path ...../qc_report/report_barcoding.html \
               --data-report-path ..../qc_report/report_barcoding.data \
               --barcoding  \ 
               --barcodes barcode01:barcode15
```

Hope that will help 🙂

Best regards,
Ali

**Comment by ZTehrani** [comment]
Thank you Ali for your help. The issue is fixed :)
