### ISSUE TITLE
Invalid type for the value of the key n50: <class 'NoneType'>

### ISSUE THREAD

**Issue by ZTehrani** [GenomiqueENS/toulligQC#33]
Hello ToulligQC Team,

I have used Dorado to do basecalling and demultiplexing of my reads. Now to create the QC report using ToulligQC version 2.6, I first renamed the column _barcode_ to _barcode arrangement_ in basecalling summary file, then removed the barcoding kit name from barcodes. I am getting this error and don't understand what is causing that. Would appreciate your help

ToulligQC version 2.6
* Initialize extractors
* Start Toulligqc info extractor
* End of Toulligqc info extractor (done in 0m0.00s)
* Start Pod5 extractor
* End of Pod5 extractor (done in 0m0.04s)
* Start Basecaller sequencing summary extractor
  - Load sequencing summary file (913.38 MB used) in 1m8.76s
Traceback (most recent call last):
  File "/usr/local/bin/toulligqc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/toulligqc/toulligqc.py", line 398, in main
    extractor.extract(result_dict)
  File "/usr/local/lib/python3.11/site-packages/toulligqc/sequencing_summary_extractor.py", line 223, in extract
    set_result_value(self, result_dict, "n50", compute_NXX(self.dataframe_dict, 50))
  File "/usr/local/lib/python3.11/site-packages/toulligqc/extractor_common.py", line 39, in set_result_value
    _check_result_key_value(key, value)
  File "/usr/local/lib/python3.11/site-packages/toulligqc/extractor_common.py", line 66, in _check_result_key_value
    raise TypeError("Invalid type for the value of the key {}: {} ".format(key, type(value)))
TypeError: Invalid type for the value of the key n50: <class 'NoneType'>

The command I ran: 

 **toulligqc --report-name** 'Sequencing Report' **--sequencing-summary-source** [path to basecalling summary] **--pod5-source** [path to pod5 files] **--html-report-path** report.html **--data-report-path** report.data --barcoding --barcodes barcode01,barcode02,barcode03,barcode04,barcode05,barcode06,barcode07,barcode08,barcode09,barcode10,barcode11,barcode12,barcode13,barcode14,barcode15,barcode16,barcode17,barcode18,barcode19,barcode20,barcode21,barcode22,barcode23,barcode24,barcode25,barcode26,barcode27,barcode28,barcode29,barcode30,barcode31,barcode32,barcode33,barcode34,barcode35,barcode36,barcode37,barcode38,barcode39,barcode40,barcode41,barcode42,barcode43,barcode44,barcode45,barcode46,barcode47,barcode48

**Comment by alihamraoui** [comment]
Hi @ZTehrani,

It seems that you're encountering the same issue as in #28. We addressed this in [toulligQC v2.7.1](https://github.com/GenomiqueENS/toulligQC/pull/31). Please try installing the newer version.

Since it's just a compatibility issue with Pandas, you can also resolve the problem by installing pandas==2.1.4 and numpy==1.26.4 via pip.

Best regards,
Ali

**Comment by alihamraoui** [comment]
As a quick tip, you can use `--barcodes barcode01:barcode48` instead of listing each barcode individually from `barcode01` to `barcode48`. 😉
