### ISSUE TITLE
Integration with EPI2ME (nexflow)

### ISSUE THREAD

**Issue by emeraldojo** [GenomiqueENS/toulligQC#36]
Hi GenomiqueENS,

since I could previously integrate the ToulligQC v.1.2 directly into Epi2ME as wf-ToulligQC and it has been great serving as QC steps in many experiments / troubleshootings. Would it be possible for the newer versions to do the same? Thanks in advance.

**Comment by alihamraoui** [comment]
Hi @emeraldojo,

The newer version, ToulligQC 2.7, is already integrated into EPI2ME Labs. You can find more details in the GitHub repository: https://github.com/GenomiqueENS/wf-toulligqc.

I hope this answers your question!

Best regards,
Ali

**Comment by emeraldojo** [comment]
Thank you so much! Very much appreciated
